# Generated by Django 5.2.17 on 2026-09-17 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=1.0)),
                ('style_override', models.JSONField(blank=True, help_text="Per-map override of the layer's default style", null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='layers.layerinfo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MapProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('basemap_style', models.CharField(default='mapbox://styles/mapbox/streets-v12', max_length=255)),
                ('center_lng', models.FloatField(default=0)),
                ('center_lat', models.FloatField(default=0)),
                ('zoom', models.FloatField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layers', models.ManyToManyField(related_name='maps', through='maps.MapLayer', to='layers.layerinfo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'permissions': [('share_mapproject', 'Can share maps with other users')],
            },
        ),
        migrations.AddField(
            model_name='maplayer',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='maps.mapproject'),
        ),
        migrations.AlterUniqueTogether(
            name='maplayer',
            unique_together={('map', 'layer')},
        ),
        migrations.CreateModel(
            name='MapShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View only'), ('edit', 'Can edit layers & layout')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='maps.mapproject')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_shares_granted', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('map', 'shared_with')},
            },
        ),
    ]
