# Generated by Django 5.2.17 on 2026-09-17 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('schema_name', models.CharField(max_length=63)),
                ('table_name', models.CharField(max_length=63, unique=True)),
                ('geometry_type', models.CharField(choices=[('Point', 'Point'), ('MultiPoint', 'MultiPoint'), ('LineString', 'LineString'), ('MultiLineString', 'MultiLineString'), ('Polygon', 'Polygon'), ('MultiPolygon', 'MultiPolygon'), ('Geometry', 'Geometry')], default='Geometry', max_length=30)),
                ('srid', models.IntegerField(default=4326)),
                ('feature_count', models.IntegerField(default=0)),
                ('bounds', models.JSONField(blank=True, help_text='[minx, miny, maxx, maxy] in EPSG:4326', null=True)),
                ('attribute_schema', models.JSONField(blank=True, default=list, help_text='[{name, type}] of imported columns')),
                ('style', models.JSONField(blank=True, default=dict, help_text='MapLibre/Mapbox GL paint+layout style')),
                ('label_config', models.JSONField(blank=True, default=dict, help_text='{field, min_zoom, text_color, ...}')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('upload_layerinfo', 'Can upload new layers'), ('share_layerinfo', 'Can share layers with other users')],
            },
        ),
        migrations.CreateModel(
            name='LayerShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View only'), ('edit', 'Can edit style & labels')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='layers.layerinfo')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_shares_granted', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_layers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('layer', 'shared_with')},
            },
        ),
    ]
